sudo: required

language: python

python:
  - "3.5"

env:
  - PYTHON3_VERSION=3.5
  - PYTHON3_VERSION=3.6

install:
  - ./install-docker.sh
  - ./install-docker-compose.sh
  - pip install codecov

before_script:
  - docker -v
  - docker-compose -v
  - printenv

script:
  - ./run-tests.sh

after_success:
  - codecov
