version: '3'

services:
  alcor:
    build: .
    image: lycantropos/alcor:0.0.0
    entrypoint: python3
    volumes:
      - .:/alcor/
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    command: setup.py test
    environment:
      - POSTGRES_URI=postgresql://username:password@postgres/alcor
