version: '3'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=alcor
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    networks:
      - alcor_default

volumes:
  postgres-data:

networks:
  alcor_default:
    external:
      name: alcor_default
