version: '3'

services:
  alcor:
    build:
      context: .
      args:
        - PYTHON3_VERSION=$PYTHON3_VERSION
    image: lycantropos/alcor:0.0.0
    entrypoint: "/alcor/docker-entrypoint.sh"
    volumes:
      - .:/alcor/
    extra_hosts:
      dockerhost: $DOCKERHOST  # for debugging
    command:
      # Generating stars:
      - simulate
      - --project-dir
      - test_project
      - --clean
    environment:
      POSTGRES_URI: $POSTGRES_URI
      FORTRAN_COMPILER_OPTIONS: "
      -g -fbacktrace -ffpe-trap=zero,overflow,invalid -Wall
      -Wextra -Wconversion -fbounds-check -fcheck=all -fmax-errors=5"
