version: '3'

services:
  alcor:
    build: .
    image: lycantropos/alcor:latest
    entrypoint: "/alcor/docker-entrypoint.sh"
    volumes:
      - .:/alcor/
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    command:
        # Processing generated data:
        - process
        - --last=1
#        - --group_id=77066762-28da-4c62-b0cc-18e73a942f97
#        - --filtration-method
#        - restricted
        - --nullify-radial-velocity
        - --w-velocities-vs-magnitude
        - --w-lepine-criterion
    environment:
      - POSTGRES_URI=postgresql://username:password@postgres/alcor

  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=alcor
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  postgres-data:
