version: '3'

services:
  alcor:
    build:
      context: .
      args:
        - PYTHON3_VERSION=$PYTHON3_VERSION
    image: lycantropos/alcor:0.0.0
    entrypoint: "/alcor/docker-entrypoint.sh"
    volumes:
      - .:/alcor/
    extra_hosts:
      dockerhost: $DOCKERHOST  # for debugging
    command:
      # Plotting
      - plot
#      - --group_id=77066762-28da-4c62-b0cc-18e73a942f97
      - --filtration-method
      - restricted
#      - --nullify-radial-velocity
#      - --lepine-criterion
      - --luminosity-function
#      - --velocities-vs-magnitude
#      - --velocity-clouds
#      - --heatmap
#      - velocities
#      - --toomre-diagram
#      - --ugriz-color-color-diagram
    environment:
      POSTGRES_URI: $POSTGRES_URI
