version: '3'

services:
  alcor:
    build:
      context: .
      args:
        - PYTHON3_VERSION=$PYTHON3_VERSION
    image: lycantropos/alcor:0.0.0
    entrypoint: python3
    volumes:
      - .:/alcor/
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    command: setup.py test
    environment:
      POSTGRES_URI: $POSTGRES_URI
