version: '3'

services:
  alcor:
    build:
      context: .
      args:
        - PYTHON3_VERSION=$PYTHON3_VERSION
        - FORTRAN_COMPILER_OPTIONS=$FORTRAN_COMPILER_OPTIONS
    image: lycantropos/alcor:0.0.0
    volumes:
      - ./test_project:/alcor/test_project
      - ./alcor:/alcor/alcor
      - ./tests:/alcor/tests
      - ./README.rst:/alcor/README.rst
      - ./setup.py:/alcor/setup.py
      - ./setup.cfg:/alcor/setup.cfg
      - ./settings.yml:/alcor/settings.yml
      - ./requirements.txt:/alcor/requirements.txt
      - ./manage.py:/alcor/manage.py
    extra_hosts:
      dockerhost: $DOCKERHOST  # for debugging
    command:
      - simulate
      - --project-dir
      - test_project
      - --clean
    environment:
      POSTGRES_URI: $POSTGRES_URI
