version: '3'

services:
  alcor:
    build: .
    image: lycantropos/alcor:0.0.0
    entrypoint: python3
    volumes:
      - .:/alcor/
    command: setup.py test
    environment:
      - POSTGRES_URI=postgresql://username:password@postgres/alcor

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=alcor
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
