version: '3'

services:
  postgres:
    image: postgres::9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=alcor
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  postgres-data:
