model_type: 1

# specifies to which decimal place
# floating point numbers should be rounded
precision: 6

parameters:
  DB_fraction:
    start: 0.2
    step: 0.1
    count: 1

  galaxy_age:
    start: 9.2
    step: 0.5
    count: 1

  initial_mass_function_exponent:
    start: -2.35
    step: 0.1
    count: 1

  lifetime_mass_ratio:
    start: 1.0
    step: 0.1
    count: 1

  burst_time:
    start: 0.6
    step: 0.1
    count: 1

  mass_reduction_factor:
    start: 0.3
    step: 0.1
    count: 1
