precision: 6

# TODO: Change to thick-to-thin disks number of stars fraction
model_type: 2

geometry: sphere

parameters:
  commons:
#   TODO: this is not applied to cone
    burst_time: 0.6
    DB_fraction: 0.2
#   TODO: there are other values for cone
    galaxy_age: 9.2
    initial_mass_function_exponent: -2.35
    lifetime_mass_ratio: 1.0
#   TODO: apply this for cone also
    mass_reduction_factor: 5.0
  cones:
    longitudes:
      csv: ../legacy.csv
      column: 8
    latitudes:
      csv: ../legacy.csv
      column: 9
