precision: 6

model_type: 2

geometry: cone

parameters:
  commons:
    burst_time: 0.6
    DB_fraction: 0.2
    galaxy_age:
      start: 9.2
      step: 0.5
      count: 2
    initial_mass_function_exponent: -2.35
    lifetime_mass_ratio: 1.0
    mass_reduction_factor: 3.7
  cone:
    longitude:
      csv: ../plates_info_arebassa_0.csv
      column: 8
    latitude:
      csv: ../plates_info_arebassa_0.csv
      column: 9
