precision: 6

model_type: 2

geometry: sphere

parameters:
  commons:
    burst_time: 0.6
    DB_fraction: 0.2
    galaxy_age: 9.2
    initial_mass_function_exponent: -2.35
    lifetime_mass_ratio: 1.0
    mass_reduction_factor: 5.0
  cone:
    longitude:
      csv: ../cone_plates_no_repetitions.csv
      column: 8
    latitude:
      csv: ../cone_plates_no_repetitions.csv
      column: 9
