precision: 6

geometry: sphere

parameters:
  commons:
#   TODO: this is not applied to cone
    burst_time: 0.6
    DB_fraction: 0.2
#   TODO: there are other values for cone
    galaxy_age: 9.2
    initial_mass_function_exponent: -2.35
    lifetime_mass_ratio: 1.0
    mass_reduction_factor: 0.03
  cones:
    thick_disk_stars_fraction: 0.8
    longitudes:
      csv: ../legacy.csv
      column: 8
    latitudes:
      csv: ../legacy.csv
      column: 9
